language: node_js
node_js:
    - '12'
branches:
    only:
        - master
services:
    - postgresql
before_script:
    - psql --version
    - make postgres-setup
script:
    - node --version
    - npm --version
    - npm test
after_success:
    - npm run coverage
    - bash <(curl -s https://codecov.io/bash)
