language: node_js
node_js:
    - '12'
branches:
    only:
        - master
script:
    - node --version
    - npm --version
    - npm test
after_success:
    - npm run coverage
    - bash <(curl -s https://codecov.io/bash)
